// Englische Songs – komplette Liste
const list = document.getElementById("songlist");

songs.forEach(song => {
    const li = document.createElement("li");
    const title = song.split("/").pop().replace(".mp3", "");

    li.innerHTML = `
        <a href="${song}">${title}</a>
        <a href="${song}" download class="download-btn">Download</a>
    `;
    list.appendChild(li);
});
const songs = [
    "../txt/Alle Menschen sind bald Brüder_engl.mp3",
    "../txt/Am liebsten bin ich glücklich_engl.mp3",
    "../txt/Bald wird alles gut_engl.mp3",
    "../txt/Bevor die Welt im Feuer steht_engl.mp3",
    "../txt/Bleib bei mir_engl.mp3",
    "../txt/Blumen suchen die Sonne_engl.mp3",
    "../txt/Bist du allein schöne Lady_engl.mp3",
    "../txt/Brennendes Herz-Country-Pop-Ballade_engl.mp3",
    "../txt/Chef dieser Welt_engl.mp3",
    "../txt/Country-Fieber hält mich wach_engl.mp3",
    "../txt/Country-Lady_engl.mp3",
    "../txt/Darling deine Augen leuchten_engl.mp3",
    "../txt/Das Wunder der Liebe_engl.mp3",
    "../txt/Dein Bild_engl.mp3",
    "../txt/Der Country-Beat ist mein Zuhaus_engl.mp3",
    "../txt/Der Country-Song lässt mich nicht los_engl.mp3",
    "../txt/Der Highway ruft_engl.mp3",
    "../txt/Der Himmel der uns kennt_engl.mp3",
    "../txt/Der Himmel schickt Tränen_engl.mp3",
    "../txt/Die Erde dreht sich_engl.mp3",
    "../txt/Die Ferne ist mein Zuhaus_engl.mp3",
    "../txt/Die kleinen Wunder_engl.mp3",
    "../txt/Die Nacht hält uns fest_engl.mp3",
    "../txt/Die Sehnsucht bleibt Duett_engl.mp3",
    "../txt/Die Sonne scheint_engl.mp3",
    "../txt/Die Welt ist einfach schön_engl.mp3",
    "../txt/Du bist das Licht in meiner Nacht_engl.mp3",
    "../txt/Du bist der Beat in mir_engl.mp3",
    "../txt/Du bist ein Lied in mir_engl.mp3",
    "../txt/Du bist hier nicht allein_engl.mp3",
    "../txt/Du bist mein Licht in meiner Nacht_engl.mp3",
    "../txt/Du bist meine Welt_engl.mp3",
    "../txt/Du bist wertvoll_engl.mp3",
    "../txt/Du liebst mich_engl.mp3",
    "../txt/Ein Duft der bleibt_engl.mp3",
    "../txt/Ein Herz das von Liebe erzählt_engl.mp3",
    "../txt/Ein Leben lang bei dir Duett_engl.mp3",
    "../txt/Einsam sah ich dich stehn_engl.mp3",
    "../txt/Es begann in Waging_engl.mp3",
    "../txt/Ganz nahe bei dir_engl.mp3",
    "../txt/Gegen den Sturm_60s_Rock'n'Roll_engl.mp3",
    "../txt/Gedanken gehen auf die Reise F_engl.mp3",
    "../txt/Glücklich sein für immer_Duett_engl.mp3",
    "../txt/Große Gefühle tragen uns_engl.mp3",
    "../txt/Habgier frisst die Heimat Erde_engl.mp3",
    "../txt/Hände jetzt nach oben_engl.mp3",
    "../txt/Heimweh-Liebe wohnt in dir_engl.mp3",
    "../txt/Hör die Melodie von damals_engl.mp3",
    "../txt/Ich hab dich verloren_engl.mp3",
    "../txt/Ich halt dich fest in jeder Nacht_engl.mp3",
    "../txt/Ich spüre das Leben_Duett_engl.mp3",
    "../txt/Ich steh im Kreis der Flammen_engl.mp3",
    "../txt/Ich steh zu dir_Duett_engl.mp3",
    "../txt/Ich suche neue Wege_engl.mp3",
    "../txt/Ich träumte vom Frieden_engl.mp3",
    "../txt/Kein Traum ist zu groß_engl.mp3",
    "../txt/Kinder rufen nach Liebe_engl.mp3",
    "../txt/Knutschen will gelernt sein_engl.mp3",
    "../txt/Körner aus Sand auf deiner Hand_engl.mp3",
    "../txt/Kroatien wir grüßen dich_engl.mp3",
    "../txt/Liebe Glück in Ewigkeit_engl.mp3",
    "../txt/Liebe ohne Schmerzen_engl.mp3",
    "../txt/Manchmal_engl.mp3",
    "../txt/My High School Sweetheart_engl.mp3",
    "../txt/My Lady Sonja_engl.mp3",
    "../txt/Nachtgedanken_engl.mp3",
    "../txt/Nur mit dir_Duett-Ballade_engl.mp3",
    "../txt/Nur mit dirn F_engl.mp3",
    "../txt/Odessa meine Heimat uk.mp3",
    "../txt/Party im San Francisco_engl.mp3",
    "../txt/Rock'n'Roll in unsrer Zeit_engl.mp3",
    "../txt/Sag mir doch ob du mich liebst_engl.mp3",
    "../txt/So leicht wie heut_engl.mp3",
    "../txt/Sofort hast du mich elektrisiert_engl.mp3",
    "../txt/Sommerherz_engl.mp3",
    "../txt/Sommerliebe am Strand_engl.mp3",
    "../txt/Sonja du bist alles_engl.mp3",
    "../txt/Sonja mein Traum_engl.mp3",
    "../txt/Sternenwind_engl.mp3",
    "../txt/Tausche nicht die Sonne_engl.mp3",
    "../txt/Traum meiner schlaflosen Nächte_engl.mp3",
    "../txt/Unten am Strand – Soul‑Beach_engl.mp3",
    "../txt/Unten in den Gassen_engl.mp3",
    "../txt/Um die halbe Welt_engl.mp3",
    "../txt/Und wieder ruf ich deinen Namen_engl.mp3",
    "../txt/Vergessen hier Vergessen dort Rock'n'Roll_engl.mp3",
    "../txt/Wahre Liebe geht nie verloren_engl.mp3",
    "../txt/Warum nicht ich_engl.mp3",
    "../txt/Weißt du den Weg zurück_engl.mp3",
    "../txt/Weißt du wie heiß die Sehnsucht brennt_engl.mp3",
    "../txt/Wenn du mich liebst küss mich_engl.mp3",
    "../txt/Wenn man einander liebt_engl.mp3",
    "../txt/Wie lange willst du glücklich sein_Duett_engl.mp3",
    "../txt/Wieviel Tränen braucht das Leben_engl.mp3",
    "../txt/Wilde Pferde ziehn mich heim_engl.mp3"
];


    list.appendChild(li);
});

